### ISSUE TITLE
sexy PS1 

### ISSUE THREAD

**Issue by diehard88** [skittles9823/terminalmods#1]
why was this added in .bashrc?

# Sexy af PS1
export PS1="${green}┌|\@${cyan} ${HOSTNAME} at ${host}${purple} in \W \n${green}└─${blank} \$ "

**Comment by skittles9823** [comment]
The PS1 variable is the main visible prompt, this is what the one in terminal mods looks like.

![ps1](https://i.imgur.com/JuJy7G7.png)

**Comment by skittles9823** [comment]
the PS1 variable is the prompt you'll see.

**Comment by diehard88** [comment]
@skittles9823 

Thanks!   This variable was modified in the last update, correct?

**Comment by skittles9823** [comment]
No it wasn't, you can check the commit history over at https://github.com/Magisk-Modules-Repo/terminalmods/commits/master for exactly what changed.
