### ISSUE TITLE
ls --group-directories-first

### ISSUE THREAD

**Issue by diehard88** [skittles9823/terminalmods#2]
The command ls --group-directories-first fails under su shell as shown in screenshot.
Did I miss something?

.
![](https://i.imgur.com/sk3a7Mm.jpg)

**Comment by skittles9823** [comment]
Set $PATH in .bashrc to this:

`PATH=$BBDIR:/sbin:.$PATH`

**Comment by diehard88** [comment]
thanks.


which one in particular?

/sdcard/.bashrc has it as seen in screenshot   below.

![](https://i.imgur.com/Ww5EWkb.jpg)

**Comment by skittles9823** [comment]
@diehard88 yea pretty much switch the positions of ${PATH} and ${BBDIR}

**Comment by diehard88** [comment]
@skittles9823 

sorry, I meant which .bashrc should  I modify?   There are two .bashrc files.


Thanks!

**Comment by skittles9823** [comment]
The one in /sdcard
